language: ruby
rvm:
  - 2.3.0

before_script:
  - psql -c "CREATE USER brass_bull WITH PASSWORD 'brass_bull';" -U postgres
  - psql -c 'create database brass_bull_test;' -U postgres

script:
  - bin/rake db:migrate RAILS_ENV=test
  - bin/rake bundle exec rspec
